PROBLEM = 'Problem'
PREPROCESS = 'Pre-processing time'
MAXMEM = 'Max Memory'
SAT = 'Sat'
MODELS = 'Models'
CALLS = 'Calls'
SOLVING = 'Solve Time'
MODEL1st = '1st Model Time'
TIMEUNSAT = 'Unsat Time'
CPUTIME = 'CPU Time'
STATE_N = 'States'
ACTION_N = 'Actions'
STDOUT = 'Stdout'
RESULT = 'Result'
SYMBOLS= 'symbols'
RULES = 'rules'
VARIABLES = 'variables'
CONSTRAINTS = 'constraints'
CHOICES = 'choices'
CONFLICTS = 'conflicts'
OPTIMUM= 'optimum'
OPTIMIZATION= 'optimization'

NAME = 'name'
OUTPUT = 'output'
TIME = 'time'
MEMORY = 'memory'
NODES = 'nodes'
EDGES = 'edges'


STATUS = 'Status'
TIMEOUT = 'Timeout'
MEMOUT = 'Memory out'
FINISH = 'Finished'